run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gofmt
    - goimports
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
  gofmt:
    simplify: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocritic
        - gosec
    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
