/**
 * Environment variables that control inference routing: which provider to use,
 * which endpoint to hit, and which model IDs to send.
 *
 * When HAWK_CODE_PROVIDER_MANAGED_BY_HOST is truthy in the spawn env, these
 * are stripped from settings-sourced env so the host's routing config isn't
 * overridden by a user's ~/.hawk/settings.json.
 */
const PROVIDER_MANAGED_ENV_VARS = new Set([
  // The flag itself — settings can't unset it once the host set it
  'HAWK_CODE_PROVIDER_MANAGED_BY_HOST',
  // Endpoint config
  'GRAYCODE_BASE_URL',
  'GRAYCODE_API_KEY',
  // Auth
  'GRAYCODE_AUTH_TOKEN',
  'HAWK_CODE_OAUTH_TOKEN',
  // Model defaults
  'GRAYCODE_MODEL',
  'GRAYCODE_DEFAULT_HAIKU_MODEL',
  'GRAYCODE_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'GRAYCODE_DEFAULT_HAIKU_MODEL_NAME',
  'GRAYCODE_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'GRAYCODE_DEFAULT_OPUS_MODEL',
  'GRAYCODE_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'GRAYCODE_DEFAULT_OPUS_MODEL_NAME',
  'GRAYCODE_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'GRAYCODE_DEFAULT_SONNET_MODEL',
  'GRAYCODE_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'GRAYCODE_DEFAULT_SONNET_MODEL_NAME',
  'GRAYCODE_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  'GRAYCODE_SMALL_FAST_MODEL',
  'HAWK_CODE_SUBAGENT_MODEL',
])

const PROVIDER_MANAGED_ENV_PREFIXES: string[] = []

export function isProviderManagedEnvVar(key: string): boolean {
  const upper = key.toUpperCase()
  const legacyMapped = upper.startsWith('GRAYCODE_')
    ? `GRAYCODE_${upper.slice('GRAYCODE_'.length)}`
    : upper
  return (
    PROVIDER_MANAGED_ENV_VARS.has(upper) ||
    PROVIDER_MANAGED_ENV_VARS.has(legacyMapped) ||
    PROVIDER_MANAGED_ENV_PREFIXES.some(
      p => upper.startsWith(p) || legacyMapped.startsWith(p),
    )
  )
}

/**
 * Dangerous shell settings that can execute arbitrary shell code
 */
export const DANGEROUS_SHELL_SETTINGS = [
  'apiKeyHelper',
  'awsAuthRefresh',
  'awsCredentialExport',
  'gcpAuthRefresh',
  'otelHeadersHelper',
  'statusLine',
] as const

/**
 * Safe environment variables that can be applied before trust dialog.
 * These are Hawk specific settings that don't pose security risks.
 *
 * IMPORTANT: This is the source of truth for which env vars are safe.
 * Any env var NOT in this list is considered dangerous and will trigger
 * a security dialog when set via remote managed settings.
 *
 * Dangerous env vars (NOT in this list):
 *
 * === REDIRECT TO ATTACKER-CONTROLLED SERVER ===
 * - GRAYCODE_BASE_URL
 * - HTTP_PROXY, HTTPS_PROXY, NO_PROXY, http_proxy, https_proxy, no_proxy
 * - OTEL_EXPORTER_OTLP_ENDPOINT, OTEL_EXPORTER_OTLP_LOGS_ENDPOINT, OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
 *
 * === TRUST ATTACKER-CONTROLLED SERVER ===
 * - NODE_TLS_REJECT_UNAUTHORIZED
 * - NODE_EXTRA_CA_CERTS
 *
 * === SWITCH TO ATTACKER-CONTROLLED PROJECT ===
 * - GRAYCODE_API_KEY, GRAYCODE_AUTH_TOKEN
 */
export const SAFE_ENV_VARS = new Set([
  'GRAYCODE_CUSTOM_HEADERS',
  'GRAYCODE_CUSTOM_MODEL_OPTION',
  'GRAYCODE_CUSTOM_MODEL_OPTION_DESCRIPTION',
  'GRAYCODE_CUSTOM_MODEL_OPTION_NAME',
  'GRAYCODE_DEFAULT_HAIKU_MODEL',
  'GRAYCODE_DEFAULT_HAIKU_MODEL_DESCRIPTION',
  'GRAYCODE_DEFAULT_HAIKU_MODEL_NAME',
  'GRAYCODE_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES',
  'GRAYCODE_DEFAULT_OPUS_MODEL',
  'GRAYCODE_DEFAULT_OPUS_MODEL_DESCRIPTION',
  'GRAYCODE_DEFAULT_OPUS_MODEL_NAME',
  'GRAYCODE_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES',
  'GRAYCODE_DEFAULT_SONNET_MODEL',
  'GRAYCODE_DEFAULT_SONNET_MODEL_DESCRIPTION',
  'GRAYCODE_DEFAULT_SONNET_MODEL_NAME',
  'GRAYCODE_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES',
  'GRAYCODE_MODEL',
  'GRAYCODE_SMALL_FAST_MODEL',
  'AWS_DEFAULT_REGION',
  'AWS_PROFILE',
  'AWS_REGION',
  'BASH_DEFAULT_TIMEOUT_MS',
  'BASH_MAX_OUTPUT_LENGTH',
  'BASH_MAX_TIMEOUT_MS',
  'HAWK_BASH_MAINTAIN_PROJECT_WORKING_DIR',
  'HAWK_CODE_API_KEY_HELPER_TTL_MS',
  'HAWK_CODE_DISABLE_EXPERIMENTAL_BETAS',
  'HAWK_CODE_DISABLE_NONESSENTIAL_TRAFFIC',
  'HAWK_CODE_DISABLE_TERMINAL_TITLE',
  'HAWK_CODE_ENABLE_TELEMETRY',
  'HAWK_CODE_EXPERIMENTAL_AGENT_TEAMS',
  'HAWK_CODE_IDE_SKIP_AUTO_INSTALL',
  'HAWK_CODE_MAX_OUTPUT_TOKENS',
  'HAWK_CODE_SUBAGENT_MODEL',
  'DISABLE_AUTOUPDATER',
  'DISABLE_BUG_COMMAND',
  'DISABLE_COST_WARNINGS',
  'DISABLE_ERROR_REPORTING',
  'DISABLE_FEEDBACK_COMMAND',
  'DISABLE_TELEMETRY',
  'ENABLE_TOOL_SEARCH',
  'MAX_MCP_OUTPUT_TOKENS',
  'MAX_THINKING_TOKENS',
  'MCP_TIMEOUT',
  'MCP_TOOL_TIMEOUT',
  'OTEL_EXPORTER_OTLP_HEADERS',
  'OTEL_EXPORTER_OTLP_LOGS_HEADERS',
  'OTEL_EXPORTER_OTLP_LOGS_PROTOCOL',
  'OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE',
  'OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY',
  'OTEL_EXPORTER_OTLP_METRICS_HEADERS',
  'OTEL_EXPORTER_OTLP_METRICS_PROTOCOL',
  'OTEL_EXPORTER_OTLP_PROTOCOL',
  'OTEL_EXPORTER_OTLP_TRACES_HEADERS',
  'OTEL_LOG_TOOL_DETAILS',
  'OTEL_LOG_USER_PROMPTS',
  'OTEL_LOGS_EXPORT_INTERVAL',
  'OTEL_LOGS_EXPORTER',
  'OTEL_METRIC_EXPORT_INTERVAL',
  'OTEL_METRICS_EXPORTER',
  'OTEL_METRICS_INCLUDE_ACCOUNT_UUID',
  'OTEL_METRICS_INCLUDE_SESSION_ID',
  'OTEL_METRICS_INCLUDE_VERSION',
  'OTEL_RESOURCE_ATTRIBUTES',
  'USE_BUILTIN_RIPGREP',
])

export function isSafeEnvVar(key: string): boolean {
  const upper = key.toUpperCase()
  if (SAFE_ENV_VARS.has(upper)) return true

  if (upper.startsWith('GRAYCODE_')) {
    const legacyMapped = `GRAYCODE_${upper.slice('GRAYCODE_'.length)}`
    return SAFE_ENV_VARS.has(legacyMapped)
  }

  return false
}
